language: csharp
solution: Katas.sln

script:
  - xbuild /p:Configuration=Release Katas.sln
  - mono ./packages/xunit.runners.*/tools/xunit.console.clr4.exe ./RomanNumeralKataTests/bin/Release/RomanNumeralKataTests.dll
  - mono ./packages/xunit.runners.*/tools/xunit.console.clr4.exe ./StringCalculatorKataTests/bin/Release/StringCalculatorKataTests.dll
  